### ISSUE TITLE
EncryptedType does not work on mysql

### ISSUE THREAD

**Issue by weizwx** [kvesteri/sqlalchemy-utils#109]
Raise an exception:
"VARCHAR requires a length on dialect mysql"

**Comment by fixedd** [comment]
I know it's years later, but you can provide the length yourself with something like:

`secret = Column(EncryptedType(String(512), secret_key, AesEngine, 'pkcs5'))`

**Comment by kurtmckee** [comment]
In 2020, 710bd898 modified `EncryptedType` to use BINARY.

I don't think this is still relevant so I'm closing this.
