### ISSUE TITLE
Issue with length=16 in Alembic migrations using UUIDType

### ISSUE THREAD

**Issue by drcongo** [kvesteri/sqlalchemy-utils#129]
Hi. 

I've got an issue running Alembic upgrades (via Flask-Script / Flask-Migrate) against models using the UUIDType on a postgres DB. The generated migration comes out looking like this...

```
"""empty message

Revision ID: 3aaa9646cbda
Revises: None
Create Date: 2015-03-02 14:47:22.123134

"""

# revision identifiers, used by Alembic.
revision = '3aaa9646cbda'
down_revision = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('role')
    ### end Alembic commands ###
```

Which as you can see, adds a length=16 keyword arg to the UUIDType creation, causing this traceback...

```
Traceback (most recent call last):
  File "manage.py", line 37, in <module>
    manager.run()
  File "/vagrant/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/vagrant/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/vagrant/venv/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/vagrant/venv/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 177, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/vagrant/venv/local/lib/python2.7/site-packages/alembic/command.py", line 165, in upgrade
    script.run_env()
  File "/vagrant/venv/local/lib/python2.7/site-packages/alembic/script.py", line 382, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/vagrant/venv/local/lib/python2.7/site-packages/alembic/util.py", line 242, in load_python_file
    module = load_module_py(module_id, path)
  File "/vagrant/venv/local/lib/python2.7/site-packages/alembic/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "migrations/env.py", line 73, in <module>
    run_migrations_online()
  File "migrations/env.py", line 66, in run_migrations_online
    context.run_migrations()
  File "<string>", line 7, in run_migrations
  File "/vagrant/venv/local/lib/python2.7/site-packages/alembic/environment.py", line 742, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/vagrant/venv/local/lib/python2.7/site-packages/alembic/migration.py", line 305, in run_migrations
    step.migration_fn(**kw)
  File "/vagrant/migrations/versions/3aaa9646cbda_.py", line 22, in upgrade
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(length=16), nullable=False),
TypeError: <flask_script.commands.Command object at 0x7fc608176250>: __init__() got an unexpected keyword argument 'length'
```

Is the length argument necessary? Is there a way to have it not there? Or am I best off creating a MyUUIDType(UUIDType) class which will accept the length param and ignore it or something?

Thanks (and thanks for sqlalchemy-utils in general).

**Comment by mehcode** [comment]
See https://github.com/kvesteri/sqlalchemy-utils/issues/106

------

Most of our types don't work with alembic. I use alembic so the thought is that I'd get mad enough one day and add support for alembic (at the moment though I've been pretty busy).

If you'd like to get started on alembic support there are a ton of resources on the issue that I linked.

**Comment by drcongo** [comment]
Ah, thanks @mehcode - I'll see what I can do with that. btw, I have ArrowType and EncryptedType working nicely with Alembic just through adding ```import sqlalchemy_utils``` to script.py.mako. The only weirdness I've found so far is not being able to enforce limits to the type underneath EncryptedType ie: the 80 in ```encname = db.Column(EncryptedType(db.Unicode(80), key))```

**Comment by mehcode** [comment]
If you want a quick solution for the time being something like the following should work:

```
class MyUUIDType(UUIDType):
  def __repr__(self):
    return "sa.dialects.postgresql.UUID()"
```

**Comment by drcongo** [comment]
I ended up implementing the example universal GUID code from the sqlalchemy docs. I'm in love with your EncryptedType though.

**Comment by mehcode** [comment]
Awesome. Glad to hear it. A great deal of that was contributed by @konstantinoskostis; credit where credit is due and all that. FYI the key can be a function which I'm using to implement per-tenant encryption keys in a multi-tenancy application. Works great.

On the limits, there really isn't much we could do apart from generating python-side validation (as an encrypted blob is just that, a blob).

**Comment by xolan** [comment]
Just ran into this issue today. My solution was to provide a custom render_item function to the context.

```
def render_item(type_, obj, autogen_context):
    """Apply custom rendering for selected items."""

    if type_ == 'type' and isinstance(obj, sqlalchemy_utils.types.uuid.UUIDType):
        # add import for this type
        autogen_context.imports.add("import sqlalchemy_utils")
        autogen_context.imports.add("import uuid")
        return "sqlalchemy_utils.types.uuid.UUIDType(), default=uuid.uuid4"

    # default rendering for other objects
    return False


def run_migrations_online():
    # ---snip---
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_item=render_item
        )

        with context.begin_transaction():
            context.run_migrations()
```

**Comment by Sphinxs** [comment]
@xolan , how do exactly you configure this script ? I have a `manage.py` which import the models and provide a cli which I can generate the models on db... more [details](https://stackoverflow.com/questions/54055469/how-to-use-sqlalchemy-utils-in-a-sqlalchemy-model) of my setup

**Comment by dxd5581** [comment]
@xolan , thanks a million! Was able to solve my issue with **ChoiceType** using your solution.

Issue:
Trying to generate a first migration with Alembic:  

$ `alembic revision -m "First migration" --autogenerate --head head`

The versions file generated:
1) Is missing the `import sqlalchemy_utils` on top 
2) Contains generated ChoiceType fields like this: 
`sa.Column('code', sqlalchemy_utils.types.choice.ChoiceType(length=255), nullable=False)` 

Then, when running $`alembic upgrade head` you get the following 
Error: 
`
sa.Column('code', sqlalchemy_utils.types.choice.ChoiceType(length=255), nullable=False),
    TypeError: ChoiceType.__init__() got an unexpected keyword argument 'length'
` 
No idea why Alembic inserts such `length=` keyword, which is not [allowed](https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.choice).


Just modifying a bit of your `alembic/env.py` file as follows: 

```python
import sqlalchemy_utils

def render_item(type_, obj, autogen_context):
    """
    Apply custom rendering for selected items.
    """
    if type_ == 'type' and isinstance(obj, sqlalchemy_utils.types.choice.ChoiceType):
        # add import for this type
        autogen_context.imports.add("import sqlalchemy_utils")
        return "sqlalchemy_utils.types.choice.ChoiceType(choices=" + str(obj.choices) + ")"

    # default rendering for other objects
    return False

def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    configuration = config.get_section(config.config_ini_section)
    configuration["sqlalchemy.url"] = get_url()
    connectable = engine_from_config(
        configuration, prefix="sqlalchemy.", poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            render_item=render_item
        )

        with context.begin_transaction():
            context.run_migrations()
```

Worked like a charm!

**Comment by thnee** [comment]
Thanks for these examples! For anyone curious, this is what I ended up with.

```python
def render_item(type_, obj, autogen_context):
    if type_ == "type":
        if isinstance(obj, sqlalchemy_utils.types.ChoiceType):
            return "sa.String(length=255)"

        if isinstance(obj, sqlalchemy_utils.types.password.PasswordType):
            return "sa.LargeBinary(length=1137)"

    return False
```
