### ISSUE TITLE
Request Support: PasswordType Simple Hash

### ISSUE THREAD

**Issue by Septembers** [kvesteri/sqlalchemy-utils#132]
using `hashlib` hash

**Comment by mehcode** [comment]
What do you mean? 

Right now `PasswordType` uses passlib. You can chose any hash you want from https://pythonhosted.org/passlib/lib/passlib.hash.html#module-passlib.hash

```
sa.Column(PasswordType(
        schemes=[
            'md5_crypt'
        ],
    ))
```

**Comment by Septembers** [comment]
thank you.
I hope it https://pythonhosted.org/passlib/lib/passlib.hash.html adding a document to http://sqlalchemy-utils.readthedocs.org/en/latest/data_types.html#module-sqlalchemy_utils.types.password
