### ISSUE TITLE
ScalarListType as Array on Postgres

### ISSUE THREAD

**Issue by ColtonProvias** [kvesteri/sqlalchemy-utils#133]
Similar to how UUIDType uses UUID on Postgres, would it be possible to have ScalarListType use ARRAY on Postgres?

**Comment by kvesteri** [comment]
I'd like to keep ScalarListType the way it is. PostgreSQL ARRAY is different in so many ways. Personally on Postgres I always use ARRAY type instead of ScalarListType.

**Comment by ziima** [comment]
Using `ScalarListType` as a variant for ARRAY works:
```python
ARRAY(Integer).with_variant(ScalarListType(int), 'sqlite')
```
the other way around doesn't
```python
# Always rendered as TEXT type
ScalarListType(int).with_variant(ARRAY(Integer), 'postgresql')
```
due to a bug sqlalchemy/sqlalchemy#5816.
