### ISSUE TITLE
How to force a locale with TranslationHybrid in a block ?

### ISSUE THREAD

**Issue by pmarti** [kvesteri/sqlalchemy-utils#141]
Hi Konsta!

Quick question about TranslationHybrid: How would you force a given locale for a block? Ideally it'd be a context manager that would allow you things like:

```python
with translation_hybrid.force_locale('en_GB'):
    print obj.name   # obj.name_translations['en_GB']
```

Thanks

**Comment by pmarti** [comment]
Finally went for function, defined in the same module as translation_hybrid.

```
+@contextmanager
+def force_locale(locale):
+    translation_hybrid.current_locale = locale
+    yield
+    translation_hybrid.current_locale = get_locale

**Comment by kvesteri** [comment]
I think this function shouldn't be part of SA-Utils. Ideally you would want this function to be threadsafe. I've been using a fork of Flask-Babel to achieve this (see https://github.com/jpvanhal/flask-babel).

**Comment by pmarti** [comment]
Thanks for the hint, this function does the trick for me as it's only used when populating ElasticSearch indices
