### ISSUE TITLE
JSONType on MySQL can be suspect to silent value truncation

### ISSUE THREAD

**Issue by moschlar** [kvesteri/sqlalchemy-utils#164]
I just learned this the hard way, but on MySQL (at least when not in [Strict SQL Mode](https://dev.mysql.com/doc/refman/5.0/en/sql-mode.html#sql-mode-strict)), columns of type ``TEXT`` will silently truncate values, thus corrupting the JSON representation:

> If strict SQL mode is not enabled and you assign a value to a BLOB or TEXT column that exceeds the column's maximum length, the value is truncated to fit and a warning is generated. For truncation of nonspace characters, you can cause an error to occur (rather than a warning) and suppress insertion of the value by using strict SQL mode. See Section 5.1.7, “Server SQL Modes”.

(https://dev.mysql.com/doc/refman/5.0/en/blob.html)

My personal workaround was to change the column type to ``LONGTEXT``, but that of course is only postponing the problem (to a length of 2^32, which is a lot, but still).

**Comment by kvesteri** [comment]
I will no longer do any updates for JSONType. The reason is SQLAlchemy 1.1 will have native support for JSON type: http://docs.sqlalchemy.org/en/latest/changelog/migration_11.html#change-3619

Thus this type will be deprecated and removed from SA-Utils in the future.
