### ISSUE TITLE
JSONType - make it easier to use OrderedDict

### ISSUE THREAD

**Issue by torotil** [kvesteri/sqlalchemy-utils#171]
For some fields I need to use OrderedDict for my JSON dumps. Currently I create a sub-class from the JSONType:

```python
class OrderedJSONType(JSONType):
    def process_result_value(self, value, dialect):
        if dialect.name == 'postgresql':
            return value
        if value is not None:
            value = json.loads(value, object_pairs_hook=OrderedDict)
        return val
```

I think that's rather ugly because it is mainly a c&p of the original `process_result_value`. Would it be possible to add  custom keyword args for `json.dumps` and `json.loads` to JSONType?

**Comment by kvesteri** [comment]
I will no longer do any updates for JSONType. The reason is SQLAlchemy 1.1 will have native support for JSON type: http://docs.sqlalchemy.org/en/latest/changelog/migration_11.html#change-3619

Thus this type will be deprecated and removed from SA-Utils in the future.
