### ISSUE TITLE
Locale Identifier With Territory Coerced Improperly

### ISSUE THREAD

**Issue by mpkuth** [kvesteri/sqlalchemy-utils#173]
[This](https://github.com/kvesteri/sqlalchemy-utils/commit/dc83308c28e38f0be1bbfd46fa837f165f8aa73f) commit fixes parsing of Locale strings that include a territory in the identifier. However, the same issue still exists in `_coerce` on line 74. It should use `Locale.parse` as well.

If that is done, the `isinstance(value, Locale)` check on line 73 will be obsolete as `Locale.parse` already does this check. `_coerce` and `process_result_value` can be exactly the same.

**Comment by kvesteri** [comment]
Fixed as of 0.31.5
