### ISSUE TITLE
EncryptedType with date time and timezone

### ISSUE THREAD

**Issue by jssuzanne** [kvesteri/sqlalchemy-utils#184]
Hi,

At https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/types/encrypted.py#L253, the date time is formatted with isoformat. Iso format convert the date time to str with microsecond and timezone.

At https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/types/encrypted.py#L278,
the formater does not take microsecond and timezone.

It is not really a bug, but the encrypted date time can not be other than a naive date time. I understand that convert all date time format is difficult, why does not use python-dateutils to convert str 2 date time, or regex.

**Comment by nosarcasm** [comment]
Have the same issue, changed https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/types/encrypted.py#L278 to this as a hacky fix:

```
decrypted_value.split(".")[0], '%Y-%m-%dT%H:%M:%S'
```
