### ISSUE TITLE
Changes to ScalarListType don't save unless the List is copied

### ISSUE THREAD

**Issue by gberger** [kvesteri/sqlalchemy-utils#185]
Consider this:

```
from sqlalchemy_utils import ScalarListType
class Company(db.Model):
    email_domains = db.Column(ScalarListType())
```

Then somewhere in a controller, I do:

```
company.email_domains.append('example.com')
db.session.add(company)
db.session.commit()

company = Company.get_by_id(company.id)
assert company.email_domains[-1] == 'example.com'
```
The assert will fail.

Workaround is copying the list and adding the new element to it:

```
company.email_domains = company.email_domains[:] + ['example.com']
db.session.add(company)
db.session.commit()

company = Company.get_by_id(company.id)
assert company.email_domains[-1] == 'example.com'
```
The assert will pass.

I know why this happens. The list is the same object reference, so it's not marked as changed. But SQLAlchemy-Utils should not surprise the user with this behavior.

**Comment by kvesteri** [comment]
This is not a bug within SA-Utils. If you want mutation tracking like this you should first checkout: http://docs.sqlalchemy.org/en/latest/orm/extensions/mutable.html

**Comment by gberger** [comment]
Well... That should be at least documented.

And if creating mutable scalar lists is something desired by SA-Utils it could be added to the project.

I can contribute.

**Comment by kvesteri** [comment]
I wouldn't encourage either one. It really depends on the situation. Mutability tracking is very handy but it also adds significant overhead.
