### ISSUE TITLE
PasswordType not working with declarative_base

### ISSUE THREAD

**Issue by danqing** [kvesteri/sqlalchemy-utils#202]
I'm not sure what's going on but I can't really get the following working:

```py
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base, declared_attr
from sqlalchemy_utils import PasswordType

class _Base(object):
    @declared_attr
    def id(cls):
        return sa.Column(sa.Integer, primary_key=True)

Base = declarative_base(cls=_Base)

class User(Base):
    __tablename__ = 'user'
    password = sa.Column(PasswordType(schemes=['pbkdf2_sha512']))


a = User()
a.password = 'a'
a.password == 'a'   # False
```

If I let `User` inherit directly from `object`, on the other hand, it will work properly. What's special with `declarative_base`?

Thanks!

**Comment by danqing** [comment]
It looks like it's just not "flushed" correctly. If I save it to the database and then load it, it functions correctly. However, if I simply create a `user` object, it doesn't work.

**Comment by danqing** [comment]
Seems that the password type only works for entities already in the DB. I didn't find any docs related to this. Maybe it's helpful to add it somewhere?

**Comment by joepvandijken** [comment]
I had the same problem, and fixed the problem by using the documented [automatic-data-coercion](http://sqlalchemy-utils.readthedocs.org/en/latest/listeners.html#automatic-data-coercion) 

`from sqlalchemy_utils import force_auto_coercion`
`force_auto_coercion()`

But I have to admin, I only found it after reading the source and many hours of debugging.

**Comment by kvesteri** [comment]
Docs updated for PasswordType regarding automatic-data-coercion.
