### ISSUE TITLE
New LTree conflicts with SQLAlchemy latest commits

### ISSUE THREAD

**Issue by ColtonProvias** [kvesteri/sqlalchemy-utils#215]
I'm currently using the latest commit from the SQLAlchemy git (https://bitbucket.org/zzzeek/sqlalchemy.git@9e77f40a313bebffd51bb62328c6c27e63152329) and receive the following error on importing sqlalchemy_utils in Python 3.5.1 in an Alpine Linux container.

```
>>> import sqlalchemy_utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/sqlalchemy_utils/__init__.py", line 61, in <module>
    from .types import (  # noqa
  File "/usr/lib/python3.5/site-packages/sqlalchemy_utils/types/__init__.py", line 15, in <module>
    from .ltree import LtreeType  # noqa
  File "/usr/lib/python3.5/site-packages/sqlalchemy_utils/types/ltree.py", line 4, in <module>
    from sqlalchemy.dialects.postgresql.base import (
ImportError: cannot import name 'ARRAY'
```

While it doesn't affect the current version released on PyPI, thus can be a possible break coming up soon.

The change that breaks this was introduced August 2015 and can be found at https://bitbucket.org/zzzeek/sqlalchemy/commits/ceeb033054f09db3eccbde3fad1941ec42919a54#Llib/sqlalchemy/dialects/postgresql/__init__.pyF15.

A quick way to fix this would be to import `ARRAY` from `sqlalchemy.dialects.postgresql` instead of `sqlalchemy.dialects.postgresql.base`.

**Comment by kvesteri** [comment]
Thanks for reporting, fixed as of 0.32.5
