### ISSUE TITLE
Cannot filter query by PasswordType column

### ISSUE THREAD

**Issue by lobisquit** [kvesteri/sqlalchemy-utils#247]
Using this library I found an unexpected behaviour, i.e. mapped objects cannot be queried by an encrypted field, such as PasswordType. 
Since it is not covered by any test on this Column type, I would like to ask you: is this an expected behaviour or a bug?

Here it is a minimal working code that shows the problem I encountered: 
```python
from sqlalchemy import *
from sqlalchemy_utils.types.password import PasswordType
from sqlalchemy_utils import force_auto_coercion

from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship

engine = create_engine('sqlite:///test.db')

# create sqlalchemy basic objects
Base = declarative_base()

Session = sessionmaker()
Session.configure(bind=engine)
session = Session()

class User(Base):
	__tablename__ = 'users'
	id = Column(Integer, primary_key=True)

	username = Column(String, nullable=False)
	password = Column(PasswordType(schemes=['bcrypt']))

	def __repr__(self):
		return "<User(id={}, username='{}', password='{}')>]".format(self.id, self.username, self.password)

Base.metadata.create_all(engine)
force_auto_coercion()

if __name__=='__main__':
	u = User(username='admin', password='password')
	session.add(u)
	session.flush()

	# correctly print new user
	print(session.query(User).all())

	# does not find any
	print(session.query(User).filter(User.password=='password').all())
```

**Comment by frol** [comment]
It is certainly an expended behavior. In fact, if there would be a way to query passwords, it would be a completely useless implementation since password security techniques imply that even equal passwords should result in different "reflections".

**Comment by lobisquit** [comment]
Thanks for the answer @frol !
I will take a different approach then ;)

**Comment by frol** [comment]
@lobisquit You might be interested in my "real-life" RESTful API demo server implementation, which uses PasswordType field and deals with it here: https://github.com/frol/flask-restplus-server-example/blob/5fd22f9113567b1bd1562b593536afcc27e4da06/app/modules/users/models.py#L114-L129

**Comment by lobisquit** [comment]
Thanks @frol ! That's exactly what i'm looking for :+1:
