### ISSUE TITLE
LTree validation issue.

### ISSUE THREAD

**Issue by sohaibfarooqi** [kvesteri/sqlalchemy-utils#253]
Hi,
I have done `Model.query.filter(Model.path == Ltree('None.1.2'))` query using Ltree type. Can anyone guide me on how to perform LQuery and use '@>' operator using SQLAlchemyUtils.?

I was able to execute '<@', '@>' operator with following syntax:

```
subq = Model.query.with_entities(Model.path).filter(Model.id == id).subquery()
Model.query.filter(Model.path.descendant_of(subq)).all()
```

But how to perform lquery '~' using LTree('.1.2') and append it with ".*". LTree validation fail in this case. Any ideas how to do it?

**Comment by kypsibir** [comment]
Will this help?
``` python
from sqlalchemy.sql import expression
from sqlalchemy_utils.types.ltree import LQUERY

custom_lquery = '*.some.pattern'
Model.query.filter(Model.path.lquery(expression.cast(custom_lquery, LQUERY))).all()
```

**Comment by sohaibfarooqi** [comment]
@kypsibir Yes this seems to work fine :)
