### ISSUE TITLE
PasswordType + Argon2 make VARBINARY(4294967331)

### ISSUE THREAD

**Issue by item4** [kvesteri/sqlalchemy-utils#259]
Passlib 1.7.0 support argon2 type hashing. I wanted to use it as Password hasing algorithm.

But sqlalchemy-utils generate `VARBINARY(4294967331)` field. It is too huge!

Size of PasswordType is depend on `max_salt_size` value and [Argon2's `max_salt_size` in passlib impl](https://bitbucket.org/ecollins/passlib/src/9572e99efc8ab5e75dea62cf474889c9ed00ac60/passlib/handlers/argon2.py?at=default&fileviewer=file-view-default#argon2.py-123) is `MAX_UINT32`.

I think you write some notice on docs or make some arguments to PasswordType for limit salt size. Default salt size setting is `16` ([argon2_cffi(passlib recommand it)](https://github.com/hynek/argon2_cffi/blob/master/src/argon2/_password_hasher.py#L13), [passlib](https://bitbucket.org/ecollins/passlib/src/9572e99efc8ab5e75dea62cf474889c9ed00ac60/passlib/handlers/argon2.py?at=default&fileviewer=file-view-default#argon2.py-66))

**Comment by flak3** [comment]
I used a workaround 
```python
import passlib.hash
passlib.hash.argon2.max_salt_size = 16
```

**Comment by kurtmckee** [comment]
Closing due to age.
