### ISSUE TITLE
0.32.13 is missing on PyPI

### ISSUE THREAD

**Issue by jacquerie** [kvesteri/sqlalchemy-utils#265]
Hi @kvesteri, thanks for your useful library.

A few days ago you tagged a new release on GitHub (https://github.com/kvesteri/sqlalchemy-utils/releases/tag/0.32.13), but it's currently not on PyPI: https://pypi.python.org/pypi/SQLAlchemy-Utils/0.32.13. Was this intentional?

**Comment by kvesteri** [comment]
Thanks for reporting this. Now fixed :train:

**Comment by jacquerie** [comment]
Thanks to you for the quick fix!
