### ISSUE TITLE
DeprecationWarning passlib.context.CryptContext.encrypt

### ISSUE THREAD

**Issue by JoostvDoorn** [kvesteri/sqlalchemy-utils#268]
encrypt was deprecated in favor of hash, see:
https://bitbucket.org/ecollins/passlib/commits/1f7421b35b750a8f47cb0a8a2e208a839feb5e4f

```
password.py:210: DeprecationWarning: the method passlib.context.CryptContext.encrypt()
is deprecated as of Passlib 1.7, and will be removed in Passlib 2.0, use
CryptContext.hash() instead.
```

**Comment by leebenson** [comment]
any chance of merging and changing this? reported over a year ago with no movement.

**Comment by kvesteri** [comment]
PRs welcome
