### ISSUE TITLE
JSONType for Postgres save as a JSONB instead of JSON

### ISSUE THREAD

**Issue by Auha** [kvesteri/sqlalchemy-utils#273]
For the `JSONType` is saved as a `json` type on Postgres. Is there a way to make it save as a `jsonb` type instead? 

I know that for some legacy applications and some other situations there are advantages to saving things as `json`, but there should be some sort of option to save things as `jsonb` in the application. 

I am willing to do a pull request if there is some sort of design of the API.

**Comment by kvesteri** [comment]
I'm planning to get rid of this type because SQLAlchemy has it natively now, hence all development efforts should be pointed towards SA not SA-Utils.

**Comment by kageurufu** [comment]
I disagree with removing this, as sqlalchemy.types.JSON does not fall back to Text for SQLite for unit testing and such

Personally, I have a modified version of this that supports `JSONType(binary=True)` to emit JSONB columns. I'm willing to provide a PR if it would be considered for addition
