### ISSUE TITLE
UnicodeDecodeError in sqlalchemy_utils.types.encrypted

### ISSUE THREAD

**Issue by xrmx** [kvesteri/sqlalchemy-utils#275]
With 0.32.14 and python 3.4 we hit this on superset (https://github.com/airbnb/superset/issues/2600):
```
  File "/venv/lib/python3.4/site-packages/sqlalchemy_utils/types/encrypted.py", line 262, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/venv/lib/python3.4/site-packages/sqlalchemy_utils/types/encrypted.py", line 90, in decrypt
    decrypted = decrypted.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 2: invalid continuation byte
```

Any hint on what could be wrong?

**Comment by xrmx** [comment]
Sorted out, the error is returned when the key used for decryption is wrong. Is it a correct interpretation? Do you think it makes sense to catch that and return something more explicit?

**Comment by kvesteri** [comment]
Yeah I think it makes sense to catch it and return something more explicit. @mehcode what do you think?

**Comment by mehcode** [comment]
I've gotten that error a dozen times and I've just penciled in `bad key / access denied` in my error memory.

I agree something that explicitly says that would be nice.
