### ISSUE TITLE
ChoiceTypes

### ISSUE THREAD

**Issue by ben-mvi** [kvesteri/sqlalchemy-utils#276]
Hello,

I have a choice list like this:

```
STATUS_CHOICES = [
    ('new', 'New'),
    ('active', 'Active'),
    ('inactive', 'Inactive'),
    ('banned', 'Banned'),
]
```

I created the column like this:

`status = db.Column(sqlalchemy_utils.ChoiceType(STATUS_CHOICES, impl=db.String()))
`

now when I call my API it outputs with `"status": "Choice(code=active, value=Active)"`

I would rather it output put like this `"status":"Active"`

I would appreciate any advice thank you

**Comment by kvesteri** [comment]
You can inherit the type and make the ``__repr__`` return whatever you want.
