### ISSUE TITLE
how can I  query and filter ScalarListType

### ISSUE THREAD

**Issue by yogurfrul** [kvesteri/sqlalchemy-utils#317]
`
from sqlalchemy_utils import ScalarListType
`
`class Foo():
`
    ` id = db.Column(db.Integer, primary_key=True)`
    ` list = db.Column(ScalarListType(int))
`

 I can get the  label as an int list , querying the foo by id
`
        foo = Foo.query.filter(Foo.id==1).first()`
       ` foo.list is int list like [0, 0, 1, 0],
`

but how can I  get the id by  querying by list[3]==1
I can't find any clue，help me please！

**Comment by kvesteri** [comment]
ScalarListType stores values as comma-seperated strings. You can query them using string functions and operators.
