### ISSUE TITLE
Any plan to support graphql?

### ISSUE THREAD

**Issue by keyeMyria** [kvesteri/sqlalchemy-utils#331]
## Any plan to support graphql?
Is there any plan to support [graphene-sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy)?

**Comment by kvesteri** [comment]
I think the dependency should be that Graphene-SQLAlchemy depends on SA-Utils and not the other way around.

It seems this package already supports SA-Utils in some way: https://github.com/graphql-python/graphene-sqlalchemy/blob/master/graphene_sqlalchemy/converter.py#L13-L14
