### ISSUE TITLE
Add ArrayOfEnum type

### ISSUE THREAD

**Issue by izissise** [kvesteri/sqlalchemy-utils#336]
The sqlalchemy [docs](http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html#using-enum-with-array) propose an implementation of ArrayOfEnum type, it would be great that it be added to sqlalchemy-utils.

**Comment by kvesteri** [comment]
I would like to see a more generalized approach that supports other types as well (JSON / JSONB etc).
