### ISSUE TITLE
Question regarding internationalization

### ISSUE THREAD

**Issue by Dimbreath** [kvesteri/sqlalchemy-utils#352]
I've been taking a look at the example provided at: https://sqlalchemy-utils.readthedocs.io/en/latest/internationalization.html

    session.query(Article).filter(Article.name['en'] == 'Some article')

I've tried code similar to this to no avail, I get:
  
    NotImplementedError: Operator 'getitem' is not supported on this expression

Here's my code: https://gist.github.com/Dimbreath/3e3655c412bdc4aff8d8fb7a597977ce

It happens on the query line.

**Comment by kvesteri** [comment]
Fixed that code example.
