### ISSUE TITLE
Possible to use Timestamp class with automap?

### ISSUE THREAD

**Issue by flewellyn** [kvesteri/sqlalchemy-utils#387]
Is this a viable idea?  I can't guarantee that a reflected database will have "created" and "updated" columns in every table in the schema.  Is there a way I could use some sort of metadata in the database (possibly in a control table) to instruct the mixin to bind its behavior to different columns?

**Comment by olirice** [comment]
Under the hood the timestamp mixin: 
- Ensures `created` and `updated` are available columns on models
- Uses event listeners and defaults to set the values for those columns

If you're using reflection and can't be sure that every table has a `created` and `updated` column, the first bullet point will cause issues.

Try attaching event listeners on your base class listening for update and insert mapper events
https://docs.sqlalchemy.org/en/13/orm/events.html#mapper-events
you can conditionally check within the event listener that the fields exist before setting them

Something like:

```python
@sa.event.listens_for(Base, 'before_update', propagate=True)
def set_updated_if_exists(mapper, connection, target):
    # When a model has a column named updated, set the updated field to now
    if hasattr(target, 'updated'):
        target.updated = datetime.utcnow()

@sa.event.listens_for(Base, 'before_insert', propagate=True)
def set_timestamps_if_exist(mapper, connection, target):
    if hasattr(target, 'created'):
        target.created = datetime.utcnow()
    # you still need to set the updated column if it exists because the updated callback
    # will not be called for inserts
    if hasattr(target, 'updated'):
        target.updated = datetime.utcnow()
```

**Comment by flewellyn** [comment]
Ahh, so that's how the magic works.  Seems straightforward enough, thanks!
