### ISSUE TITLE
Does this project follow semantic versioning?

### ISSUE THREAD

**Issue by alvassin** [kvesteri/sqlalchemy-utils#438]
What is the best way to specify this project in requirements? Can i use this project with `~=` operator and specify it like `sqlalchemy-utils~=0.36.3`?

From one hand, this library has early version, but from another, i see that some files are 7 years old, so it looks pretty mature. So, does this project follow [semver](https://semver.org), where version consists of the MAJOR.MINOR.PATCH segments (described below)? 
- `MAJOR` for incompatible API changes,
- `MINOR` for new functionality in a backwards compatible manner
- `PATCH` version when you make backwards compatible bug fixes

If it is, don't you mind to add this information to README/CHANGELOG (so, others could find answer for this question quickly)?

**Comment by Fizzadar** [comment]
Having just been caught out by this, the answer is a resounding no (sadly).

For example: https://github.com/kvesteri/sqlalchemy-utils/blob/master/CHANGES.rst#0364-2020-04-30 drop py2.7 support on a patch version as py3.4 was dropped in https://github.com/kvesteri/sqlalchemy-utils/blob/master/CHANGES.rst#0341-2019-07-15.

+1 for semver!

**Comment by csadorf** [comment]
Would be nice to get clarification on this issue.

**Comment by jakabk** [comment]
No, obviously not, but it would be great.

**Comment by alvassin** [comment]
Thank you very much.
