### ISSUE TITLE
Read the Docs is out of date

### ISSUE THREAD

**Issue by altendky** [kvesteri/sqlalchemy-utils#466]
Last Read the Docs build was 1 year and 7 months ago:
https://readthedocs.org/projects/sqlalchemy-utils/builds/

There have been 15 releases since then:
https://pypi.org/project/SQLAlchemy-Utils/#history

This was specifically run into when someone try the first example in the `analyze()` docs and we had to dig into the source to figure out it had been removed entirely.

https://sqlalchemy-utils.readthedocs.io/en/latest/database_helpers.html#analyze

I would generally expect RTD to build every main branch commit and publish that under latest as well as the most recent release being available under stable and older versions available as their version number.  If help would be useful in addressing this, let me know.

**Comment by kvesteri** [comment]
I've done the setups mentioned here: https://docs.readthedocs.io/en/stable/webhooks.html#webhook-integration-github

However still getting the following error from the webhook:

Headers
Allow: POST, OPTIONS
Cf-Cache-Status: DYNAMIC
Cf-Ray: 5bc65d341847f19c-IAD
Cf-Request-Id: 044fd8948d0000f19c49b8f200000001
Connection: keep-alive
Content-Language: en
Content-Length: 40
Content-Security-Policy-Report-Only: frame-ancestors &#39;none&#39;; object-src &#39;none&#39;; block-all-mixed-content; report-uri https://sentry.io/api/148442/security/?sentry_key=48196e632bb14305ad3fe47c6570e363
Content-Type: application/json
Date: Sun, 02 Aug 2020 08:17:43 GMT
Expect-Ct: max-age=604800, report-uri=&quot;https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct&quot;
Server: cloudflare
Set-Cookie: __cfduid=dfec4e9f6c1c1b1210a86eb1d83e219e51596356263; expires=Tue, 01-Sep-20 08:17:43 GMT; path=/; domain=.readthedocs.org; HttpOnly; SameSite=Lax
Strict-Transport-Security: max-age=31536000;
Vary: Accept, Accept-Language, Cookie
X-Backend: web0000vq
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Body
{"detail":"Method \"GET\" not allowed."}

**Comment by altendky** [comment]
I only just got started with Read the Docs but I don't think I explicitly set up webhooks.  Rather, IIRC, I went to https://readthedocs.org/dashboard/ and clicked `Import a Project` and let RTD have some access to my GitHub stuff.  I understand that some would rather not do that, but if it doesn't worry you then maybe try to wipe out all existing GitHub setup and restart with the RTD dashboard and automatic setup.  You could even go to the point of revoking any access that RTD presently has to GitHub.

Sorry for the totally generic response.  I don't have any significant experience debugging webhooks.

**Comment by kvesteri** [comment]
Finally got it working. For anyone who is having the same problem: the webhook content-type needed to be set to "x-www-form-urlencoded" instead of "json"
