### ISSUE TITLE
Add support for SQLAlchemy 1.4

### ISSUE THREAD

**Issue by rudaporto** [kvesteri/sqlalchemy-utils#474]
I know that it's very fresh and still beta but it would be good to start preparing for that.

**Comment by matthewsmar** [comment]
Here is some more detail.

An example of the kind of errors we are currently seeing

```
/Users/mem/env/vita-homebrew/lib/python3.8/site-packages/sqlalchemy_continuum/__init__.py:3: in <module>
    from .manager import VersioningManager
/Users/mem/env/vita-homebrew/lib/python3.8/site-packages/sqlalchemy_continuum/manager.py:6: in <module>
    from sqlalchemy_utils import get_column_key
/Users/mem/env/vita-homebrew/lib/python3.8/site-packages/sqlalchemy_utils/__init__.py:1: in <module>
    from .aggregates import aggregated  # noqa
/Users/mem/env/vita-homebrew/lib/python3.8/site-packages/sqlalchemy_utils/aggregates.py:372: in <module>
    from .functions.orm import get_column_key
/Users/mem/env/vita-homebrew/lib/python3.8/site-packages/sqlalchemy_utils/functions/__init__.py:1: in <module>
    from .database import (  # noqa
/Users/mem/env/vita-homebrew/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py:11: in <module>
    from .orm import quote
/Users/mem/env/vita-homebrew/lib/python3.8/site-packages/sqlalchemy_utils/functions/orm.py:14: in <module>
    from sqlalchemy.orm.query import _ColumnEntity
E   ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/Users/mem/env/vita-homebrew/lib/python3.8/site-packages/sqlalchemy/orm/query.py)
```

**Comment by kvesteri** [comment]
PRs welcome

**Comment by jace** [comment]
`_ColumnEntity` has been relocated from `sqlalchemy.orm.query` to `sqlalchemy.orm.context`. Apart from this import, there are a couple dotted references in the file that need updating.

**Comment by jakeogh** [comment]
Using the branch from #482 and git-latest sqlalchemy:

On git-latest sqlalchemy:

```
$ ipython
Python 3.8.7 (default, Jan 31 2021, 08:59:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: /home/user >>>: from sqlalchemy_utils.functions import database_exists

In [2]: /home/user >>>: database_exists('postgresql://postgres@localhost/nope')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-9a02dbb071e9> in <module>
----> 1 database_exists('postgresql://postgres@localhost/nope')

/usr/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py in database_exists(url)
    459 
    460     url = copy(make_url(url))
--> 461     database, url.database = url.database, None
    462     engine = sa.create_engine(url)
    463 

AttributeError: can't set attribute

In [3]: /home/user >>>: from sqlalchemy_utils.functions import create_database

In [4]: /home/user >>>: create_database('postgresql://postgres@localhost/nope')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-9209dbd233cb> in <module>
----> 1 create_database('postgresql://postgres@localhost/nope')

/usr/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py in create_database(url, encoding, template)
    524 
    525     if url.drivername.startswith('postgres'):
--> 526         url.database = 'postgres'
    527     elif url.drivername.startswith('mssql'):
    528         url.database = 'master'

AttributeError: can't set attribute

In [5]: /home/user >>>: 
```

**Comment by uranusjr** [comment]
Should this be closed now that 0.37.0 is released with SQLAlchemy 1.4 support?

**Comment by gepuro** [comment]
In my environment, I solved this problem to update 0.36.8 to 0.37.0 on SQLAlchemy 1.4.

**Comment by proteeti13** [comment]
> In my environment, I solved this problem to update 0.36.8 to 0.37.0 on SQLAlchemy 1.4.

Hello! I am facing the same error. Can you help me by elaborating which library you are referring to by saying "update 0.36.8 to 0.37.0" ? Thanks.

**Comment by nsoranzo** [comment]
> Should this be closed now that 0.37.0 is released with SQLAlchemy 1.4 support?

Yes, this should be closed.

> > In my environment, I solved this problem to update 0.36.8 to 0.37.0 on SQLAlchemy 1.4.
> 
> Hello! I am facing the same error. Can you help me by elaborating which library you are referring to by saying "update 0.36.8 to 0.37.0" ? Thanks.

SQLAlchemy-Utils (latest is 0.37.2).

**Comment by vjpraagsh** [comment]
superset db upgrade
Traceback (most recent call last):
  File "/usr/local/bin/superset", line 5, in <module>
    from superset.cli import superset
  File "/usr/local/lib/python3.6/site-packages/superset/__init__.py", line 21, in <module>
    from superset.app import create_app
  File "/usr/local/lib/python3.6/site-packages/superset/app.py", line 24, in <module>
    from flask_appbuilder import expose, IndexView
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
    from .api import ModelRestApi  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/api/__init__.py", line 21, in <module>
    from .convert import Model2SchemaConverter
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/api/convert.py", line 4, in <module>
    from flask_appbuilder.models.sqla.interface import SQLAInterface
  File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/models/sqla/interface.py", line 40, in <module>
    from sqlalchemy_utils.types.uuid import UUIDType
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity'

**Comment by kurtmckee** [comment]
@vjpraagsh Please open a new issue.
