### ISSUE TITLE
choiceType raised TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by raintwice** [kvesteri/sqlalchemy-utils#511]
I define a table as follow
```
    STATUS_MAPPING = [
        (RELEASED, "online"),
        (DELETED, "offline"),
    ]

class Region(BaseModel):
    __tablename__ = 'region'
    DEFAULT_CODE = "DEFAULT"
    DEFAULT_REGION_ID = 0
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    status = db.Column(ChoiceType(BaseModel.STATUS_MAPPING, impl=db.Integer()), nullable=False)
```
When I search the db using the column name with ChoiceType, it rasie TypeError.
```
    regions = Region.query.filter(
        Region.status==Region.RELEASED,
        Region.code!=Region.DEFAULT_CODE,
    ).order_by(
        desc(Region.updated_at)
    ).all()

  File "/home/liangjiayue/Envs/mumu-store-oversea-py36-env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2685, in all
    return self._iter().all()
  File "/home/liangjiayue/Envs/mumu-store-oversea-py36-env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2823, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/liangjiayue/Envs/mumu-store-oversea-py36-env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/liangjiayue/Envs/mumu-store-oversea-py36-env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1520, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/liangjiayue/Envs/mumu-store-oversea-py36-env/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 314, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/liangjiayue/Envs/mumu-store-oversea-py36-env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1387, in _execute_clauseelement
    linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
  File "/home/liangjiayue/Envs/mumu-store-oversea-py36-env/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 531, in _compile_w_cache
    compiled_sql = compiled_cache.get(key)
  File "/home/liangjiayue/Envs/mumu-store-oversea-py36-env/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 918, in get
    item = dict.get(self, key, default)
TypeError: unhashable type: 'list'
```

I just changed the code from Python2.7 to Python3.6 and update some relative library. It worked well with Python2.7. Now with Python3.6, I wonder something incompatible caused by the new python environment.

If I don't use the columns with ChoiceType, it work well.
```
    regions = Region.query.filter(
        # Region.status==Region.RELEASED, # not use the column
        Region.code!=Region.DEFAULT_CODE,
    ).order_by(
        desc(Region.updated_at)
    ).all()
```
The version of some relative libraries are listed below.
PyMySQL 1.0.2
Flask 1.1.2
Flask-SQLALchemy 2.5.1
SQLAlchemy         1.4.7
SQLAlchemy-Utils   0.37.0

Thanks!

**Comment by raintwice** [comment]
When I change to SQLAlchemy 1.3.24, it works well.  It seems the latest SQLAlchemy-Utils hasn't follow the SQLAlchemy 1.4+. The logic of function _execute_clauseelement in sqlalchemy /engine/base.py has change since SQLAlchemy 1.4+。

**Comment by soundstripe** [comment]
I tried to track this one down for a while. After a very long time of trying to reproduce this bug with ANY other TypeDecorator, I started trying things at random. Somehow renaming the `choices` parameter to the ChoiceType constructor makes this makes the problem go away:

```
class MyChoiceType(ChoiceType):
    def __init__(self, rename_choices_for_no_reason, impl=None):
        super(MyChoiceType, self).__init__(rename_choices_for_no_reason, impl=impl)
```

Change the `rename_choices_for_no_reason` parameter name back to `choices` to see it break again.

Honestly I cannot see how this is happening.

Full minimal example:
```
# sqlalchemy 1.4.x

from sqlalchemy import Column, Integer, create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

from sqlalchemy_utils import ChoiceType

# ----------- begin fix
class ChoiceType(ChoiceType):
    def __init__(self, rename_choices_for_no_reason, impl=None):
        super(ChoiceType, self).__init__(rename_choices_for_no_reason, impl=impl)
# ----------- end fix

Base = declarative_base()


class MyClass(Base):
    __tablename__ = 'myclass'

    key = Column(Integer, primary_key=True)
    c = Column(ChoiceType([
        ('1', 'online'),
        ('2', 'offline'),
    ]))


if __name__ == '__main__':
    e = create_engine('sqlite://', echo=True)
    conn = e.connect()

    Base.metadata.create_all(e)

    s = sessionmaker(e)()
    results = s.query(MyClass).filter(MyClass.c == '2').all()
    print(results)

```

**Comment by shamilaqb** [comment]
> I tried to track this one down for a while. After a very long time of trying to reproduce this bug with ANY other TypeDecorator, I started trying things at random. Somehow renaming the `choices` parameter to the ChoiceType constructor makes this makes the problem go away:
> 
> ```
> class MyChoiceType(ChoiceType):
>     def __init__(self, rename_choices_for_no_reason, impl=None):
>         super(MyChoiceType, self).__init__(rename_choices_for_no_reason, impl=impl)
> ```
> 
> Change the `rename_choices_for_no_reason` parameter name back to `choices` to see it break again.
> 
> Honestly I cannot see how this is happening.
> 
> Full minimal example:
> 
> ```
> # sqlalchemy 1.4.x
> 
> from sqlalchemy import Column, Integer, create_engine
> from sqlalchemy.orm import declarative_base, sessionmaker
> 
> from sqlalchemy_utils import ChoiceType
> 
> # ----------- begin fix
> class ChoiceType(ChoiceType):
>     def __init__(self, rename_choices_for_no_reason, impl=None):
>         super(ChoiceType, self).__init__(rename_choices_for_no_reason, impl=impl)
> # ----------- end fix
> 
> Base = declarative_base()
> 
> 
> class MyClass(Base):
>     __tablename__ = 'myclass'
> 
>     key = Column(Integer, primary_key=True)
>     c = Column(ChoiceType([
>         ('1', 'online'),
>         ('2', 'offline'),
>     ]))
> 
> 
> if __name__ == '__main__':
>     e = create_engine('sqlite://', echo=True)
>     conn = e.connect()
> 
>     Base.metadata.create_all(e)
> 
>     s = sessionmaker(e)()
>     results = s.query(MyClass).filter(MyClass.c == '2').all()
>     print(results)
> ```

Works like a charm! Thank you.

**Comment by shamilaqb** [comment]
@soundstripe Works like a charm! Thank you.

**Comment by soundstripe** [comment]
https://groups.google.com/g/sqlalchemy/c/vssieSsehxE

Continuing discussion on sqlalchemy's mailing list

**Comment by soundstripe** [comment]
SQLAlchemy's latest change fixes this issue. TypeDecorator parameters will not be part of the cache key by default (though this will throw a warning). If you know your parameters are hashable (in your case, you could use a tuple instead of a list), you can add `cache_ok = True` as an attribute on the TypeDecorator.

In any case, I believe this issue could now be closed as far as sqlalchemy-utils is concerned.

**Comment by kvesteri** [comment]
This is now fixed

**Comment by raintwice** [comment]
Thanks!
