### ISSUE TITLE
No source package available in PyPI for 0.37.0

### ISSUE THREAD

**Issue by jarkkorantala** [kvesteri/sqlalchemy-utils#512]
The last source package (.tar.gz) submitted to PyPI is [0.36.8](https://pypi.org/project/SQLAlchemy-Utils/0.36.8/#files), but for the latest version [0.37.0](https://pypi.org/project/SQLAlchemy-Utils/0.37.0/#files) only a wheel is available.

This is an issue for the Conda recipe for the [conda-forge feedstock of sqlalchemy-utils](https://github.com/conda-forge/sqlalchemy-utils-feedstock/blob/master/recipe/meta.yaml) that expects a source package to be available in PyPI, and is currently stuck at 0.36.8. Could this be added please?

**Comment by igortg** [comment]
Not just because of conda, but I think it's a very standard practice to have the source package.

**Comment by kvesteri** [comment]
Fixed

**Comment by graingert** [comment]
@kvesteri removing distributions from releases on pypi breaks systems pinning versions see my note here https://github.com/kvesteri/sqlalchemy-utils/pull/514#issuecomment-831922847
