### ISSUE TITLE
Add support for sqlalchemy 2.0

### ISSUE THREAD

**Issue by jaapz** [kvesteri/sqlalchemy-utils#513]
For sqlalchemy 2.0, many things are deprecated. When you enable optional deprecationwarnings in 1.4 you can already prepare for these changes. Sqlalchemy utils seems to trigger a lot of these warnings, it would be nice if they were fixed

**Comment by kurtmckee** [comment]
I've opened PR #614 to introduce sqlalchemy 2.0 compatibility.

@jaapz -- and anyone who gave a thumbs-up for this ticket! -- the unit tests are passing, but if anyone could test the code in branch `sqlalchemy-2.0-issue-513` and let me know if there are additional issues in the code, I'd really appreciate it. Thanks!
