### ISSUE TITLE
Join expression support for generic relationship

### ISSUE THREAD

**Issue by kvesteri** [kvesteri/sqlalchemy-utils#52]
@mehcode I think it would be great if we could pass the allowed types to generic relationship. For example:

``` python
class User(Base):
    __tablename__ = 'user'
    id = sa.Column(sa.Integer, primary_key=True)

class Customer(Base):
    __tablename__ = 'customer'
    id = sa.Column(sa.Integer, primary_key=True)

class Event(Base):
    __tablename__ = 'event'
    id = sa.Column(sa.Integer, primary_key=True)
    object_type = sa.Column(sa.Unicode(255))
    object_id = sa.Column(sa.Integer)

    object = generic_relationship(object_type, object_id, [User, Customer])
```

This way we could control which classes the generic relationship accepts. This would also lead us to a path where we could add join expression support for generic relationships.

Consider the previous example. Now consider the following query:

``` python
session.query(Event).options(sa.orm.joinedload(Event.object))
```

This should fetch all events joined with customers and users.

What do you think?

**Comment by anandtripathi5** [comment]
How we will run join queries using sqlalchemy ex get all events of user where user is active something like that

**Comment by anishrav** [comment]
@kvesteri where is this `batch_fetch` function?

**Comment by diepquynh** [comment]
@anishrav it's 2024 and TIL that the feature was dropped back from 2015
https://github.com/kvesteri/sqlalchemy-utils/blob/baf53cd1a3e779fc127010543fed53cf4a97fe16/CHANGES.rst#0301-2015-05-06
