### ISSUE TITLE
Where is SQLAlchemy-Utils 0.37.1 ?

### ISSUE THREAD

**Issue by sileht** [kvesteri/sqlalchemy-utils#520]
Hi,

I can't find the reason why this package was deleted from pypi. 
Since this obviously breaks a lot of people's CIs, this at least needs some explanation somewhere.
So people can take action in a case of a security concern or alike etc...

If it's not a security issue, I suggest some reading about https://doughellmann.com/posts/so-youve-released-a-broken-package-to-pypi-what-do-you-do-now/

Best,

**Comment by graingert** [comment]
@sileht sqlalchemy-utils 0.37.1 is still present - just yanked https://pypi.org/project/SQLAlchemy-Utils/0.37.1/#files
