### ISSUE TITLE
yank packages with missing python_requires

### ISSUE THREAD

**Issue by graingert** [kvesteri/sqlalchemy-utils#521]
follow up to https://github.com/kvesteri/sqlalchemy-utils/pull/475 and https://github.com/kvesteri/sqlalchemy-utils/pull/519

running `pip install sqlalchemy-utils` on python 2.7 results in:

```
Collecting sqlalchemy-utils
  Downloading SQLAlchemy-Utils-0.37.0.tar.gz (135 kB)
     |████████████████████████████████| 135 kB 3.5 MB/s 
```

because it still claims to support python 2.7

so the following versions need to be yanked:

- [x] 0.36.8 (2020-07-08)
- [x] 0.36.7 (2020-07-02)
- [x] 0.36.6 (2020-05-24)
- [x] 0.37.0
- [x] 0.37.1

**Comment by graingert** [comment]
related to https://github.com/kvesteri/sqlalchemy-utils/issues/461

**Comment by graingert** [comment]
@kvesteri please can you yank these packages with invalid metadata?

**Comment by kvesteri** [comment]
Done :+1:

**Comment by graingert** [comment]
can confirm that on python2:

```
pip install sqlalchemy-utils
...
Successfully installed sqlalchemy-utils-0.36.5
```

thanks very much!
