### ISSUE TITLE
TypeDecorator UUIDType() will not produce a cache key because the `cache_ok` flag is not set to True

### ISSUE THREAD

**Issue by kevinvalk** [kvesteri/sqlalchemy-utils#524]
When using SQLAlchemy 1.4.14 that supports [cache_ok](https://docs.sqlalchemy.org/en/14/core/custom_types.html#sqlalchemy.types.TypeDecorator.cache_ok), combined with `UUIDType` from SQLAlchemy-Utils, one will get the following `SAWarning`:
```
SAWarning: TypeDecorator UUIDType() will not produce a cache key because the ``cache_ok`` flag is not set to True. 
Set this flag to True if this type object's state is safe to use in a cache key, or False to disable this warning.
```

From what I can gather this cannot be fixed by an end-user as the `cache_ok` field should be added to `UUIDType()` class within SQLALchemy-Utils.

**Comment by bibajz** [comment]
Hello, I encountered the same issue as @kevinvalk described.

If I understood the docs correctly, it depends on the hashability of the args provided to `__init__` method.

Both `binary` and `native` are `bool`, so it should be OK, I do not know about the `kwargs` though. Said `kwargs` are not used though, so can we safely delete them and add the class variable `cache_ok = True`?

```
    ...
    cache_ok = True

    def __init__(self, binary=True, native=True):
        """
        :param binary: Whether to use a BINARY(16) or CHAR(32) fallback.
        """
        self.binary = binary
        self.native = native

...
```

**Comment by bibajz** [comment]
I have tested the fix, installing my forked version made the warnings disappear. :)

However, I would like to add some tests - any direction you can point me to? What is the procedure?

@kevinvalk @kvesteri

**Comment by qtdaniel** [comment]
This may be a general problem for all custom types in `sqlalchemy-utils` since `sqlalchemy` 1.14; see https://github.com/kvesteri/sqlalchemy-utils/issues/527 for a related issue for `ArrowType`.

**Comment by sileht** [comment]
Agree I have the same issue with StringEncryptedType()
