### ISSUE TITLE
JSONType should specify hashable=false 

### ISSUE THREAD

**Issue by jessehersch** [kvesteri/sqlalchemy-utils#543]
various JSON things are not hashable. For instance lists and dicts. So the JSONType should let SQLAlchemy know that so it doesn't do things like `if value in some_dict` where value is a JSONType.

To fix this should have a `hashable = False` here:
https://github.com/kvesteri/sqlalchemy-utils/blob/b5b48b13a22aa6d796e98c0225f367a2f010c788/sqlalchemy_utils/types/json.py#L58

This causes certain use cases for JSONType to break in SQLAlchemy 1.4.19 and up. 

For background and a MCVE of the bug, see: https://github.com/sqlalchemy/sqlalchemy/issues/6924

**Comment by kurtmckee** [comment]
@jessehersch Thanks for providing code to reproduce this issue! I was able to demonstrate the issue in the unit tests, and then solve the problem using your code. Thanks for reporting this!
