### ISSUE TITLE
Decrypt StringEncryptedType mannualy in a Text sql query

### ISSUE THREAD

**Issue by caio-reimann** [kvesteri/sqlalchemy-utils#544]
I'm building a report that uses some StringEncryptedType(String(), os.environ.get("SECRET_KEY"), AesEngine, "pkcs5") columns.
For the sake of speed, I'm using text sql query.
Is possíble to decrypt StringEncryptedType() mannualy?
If yes, is there any example?

**Comment by rushilsrivastava** [comment]
This should be possible, but will vary from DB to DB. For example, you should be able to use PgCrypto with Postgres and this should work just fine as far as I know.

**Comment by caio-reimann** [comment]
I guess i found it and it was simpler than i thought

```
op = StringEncryptedType(String(), key, AesEngine, "pkcs5" )
result = op.process_result_value(value=_value_to_decrypt, dialect="str")
```
