### ISSUE TITLE
UUIDType has no `cache_ok` property, which will impact object caching

### ISSUE THREAD

**Issue by aquatix** [kvesteri/sqlalchemy-utils#567]
Using SQLAlchemy==1.4.28 and SQLAlchemy-Utils==0.37.9 I got the following message:

SAWarning: TypeDecorator UUIDType(binary=False) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)

Looking at the source of this class, it seems that this class has a pretty consistent repr, so setting that `cache_ok` property on the class would 'just work', I think?

Thanks for these nice utils and for looking into this issue, it will greatly help with our code's performance.

**Comment by artctv** [comment]
Same for SQLAlchemy == 1.4.27 and SQLAlchemy-Utils==0.37.9 for `TypeDecorator PhoneNumberType(len
gth=20)`
I think it's about how the SQLAlchemy-Utils creates own types.

**Comment by aquatix** [comment]
Yes, I think so too; I also am pretty sure it's a matter of adding that `cache_ok` property to the class definition, as I think the types are safe to cache as they are.
