### ISSUE TITLE
ChoiceType giving me integer instead of Enum before db commit

### ISSUE THREAD

**Issue by anandtripathi5** [kvesteri/sqlalchemy-utils#574]
I'm not sure whether its expected behaviour or not. The below code is working like 

```
class UserType(enum.Enum):
            admin = 1
            regular = 2


        class User(Base):
            __tablename__ = 'user'
            id = sa.Column(sa.Integer, primary_key=True)
            name = sa.Column(sa.Unicode(255))
            type = sa.Column(ChoiceType(UserType, impl=sa.Integer()))


        user = User(type=1)
        user.type  # Here user.type is returning as integer value 1 but in the docs it said it should return <UserType.admin: 1>
```
And once I do 
```
db.session.add(user)
db.session.commit()
user.type # Here user.type converts to <UserType.admin: 1>
```

Doc link: https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/types/choice.py#L84

**Comment by PresidentNick** [comment]
@anandtripathi5 will https://sqlalchemy-utils.readthedocs.io/en/latest/listeners.html#instant-defaults fix it?

**Comment by anandtripathi5** [comment]
@PresidentNick no luck with this too.

**Comment by anandtripathi5** [comment]
But thanks for pointing me to the link. On the same page I found `force_auto_coercion` https://sqlalchemy-utils.readthedocs.io/en/latest/listeners.html#sqlalchemy_utils.listeners.force_auto_coercion.

And it worked
