### ISSUE TITLE
DOC: What is the difference between sqlalchemy.dialects.postgresql.UUID and sqlalchemy_utils.types.UUIDType ?

### ISSUE THREAD

**Issue by MartinThoma** [kvesteri/sqlalchemy-utils#577]
I'm using a postgres database and I wonder if I should use [sqlalchemy.dialects.postgresql.UUID](https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#sqlalchemy.dialects.postgresql.UUID) or [sqlalchemy_utils.types.UUIDType](https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html?highlight=uuidtype#module-sqlalchemy_utils.types.uuid). What is the difference between both?

When I use the `sqlalchemy_utils` one, I get 

> SAWarning: TypeDecorator UUIDType() will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)

I don't get that message when I use `sqlalchemy.dialects.postgresql.UUID`.

**Comment by kurtmckee** [comment]
I think that `sqlalchemy_utils.types.UUIDType` implements UUID functionality for all database engines but falls back to the native column type where possible.

It's possible that #565 will address the `SAWarning` you're seeing.

**Comment by kurtmckee** [comment]
@MartinThoma Did that answer your question?

(BTW, thanks for your work on pypdf2! It's been amazing to see your work there!)

**Comment by MartinThoma** [comment]
Hahaha, the Python world is small :smile: 

Yes, it answered my question :hugs: Thank you!

I've seen for example that using the `sqlalchemy.dialects.postgresql.UUID` causes issues with sqlite, whereas sqlalchemy_utils seems to fall back to str.
