### ISSUE TITLE
Using UUIDType in WHERE comparisons

### ISSUE THREAD

**Issue by natskvi** [kvesteri/sqlalchemy-utils#579]
https://github.com/kvesteri/sqlalchemy-utils/blob/850d0ea5a8a84c0529d175ee41b9036bea597119/sqlalchemy_utils/types/uuid.py#L89

The current implementation doesn't work if I compare a `UUIDType` column (e.g. `table.c.uuid` below) to a UUID literal. For example (in the context of SQLite and assuming a row with such a UUID value actually exists),

```python
uuid_value = UUID("bb89641d-64c4-4433-975a-0085d737a5fb")
query = select(table.c).where(table.c.uuid == uuid_value)
```

To get it to work, I need to use `.hex` as follows:

```python
query = select(table.c).where(table.c.uuid == uuid_value.hex)
```

What was the rationale behind preferring

```python
return value.bytes if self.binary else value.hex
```

to

```python
return value.bytes if self.binary else str(value)
```

For example, as a result you can't implement totally generic query logic, instead requiring to check the type of the RHS operand and using a `.hex` version if it is a UUID.

Am I missing anything?

**Comment by kurtmckee** [comment]
It looks like `uuid_value.hex` and `str(uuid_value)` produce different strings:

```python
>>> print(uuid_value.hex)
'bb89641d64c44433975a0085d737a5fb'
>>> str(uuid_value)
'bb89641d-64c4-4433-975a-0085d737a5fb'
```

Reference:

https://github.com/kvesteri/sqlalchemy-utils/blob/850d0ea5a8a84c0529d175ee41b9036bea597119/sqlalchemy_utils/types/uuid.py#L75-L89

By passing in `uuid_value.hex`, the condition at line 79 triggers and converts the string _back_ to a UUID object.

What versions of sqlalchemy and sqlalchemy_utils are you using? Is it an option to post minimal code that demonstrates the bug (or add a unit test that demonstrates the bug)?

**Comment by kurtmckee** [comment]
@natskvi I'm closing this issue. If you respond back with the requested information it may be reopened.
