### ISSUE TITLE
UUID values are double-quoted in sqlalchemy >=1.4.30

### ISSUE THREAD

**Issue by kurtmckee** [kvesteri/sqlalchemy-utils#580]
Starting with sqlalchemy 1.4.30, UUID values are now quoted by sqlalchemy, including literal values. This means that [the code in sqlalchemy-utils that quotes string literals](https://github.com/kvesteri/sqlalchemy-utils/blob/2f4058b20332b5fed06a437ebd34551025504b70/sqlalchemy_utils/types/uuid.py#L73) is double-quoting UUID values.

I found this while trying to run the unit tests locally. One of the unit tests, `tests/types/test_uuid:test_literal_bind()`, fails with sqlalchemy >=1.4.30 because the SQL string that's eventually produced is:

```
"user".id = ''b4e794d6-5750-4844-958c-fa382649719d''
```

Here are the references to the sqlalchemy changes:

* [sqlalchemy commit that introduces UUID quoting](https://github.com/sqlalchemy/sqlalchemy/commit/17d228f6268515bbf37fdd70a6ee3a62cb9a0b0c)
* [sqlalchemy release 1.4.30 that introduces UUID quoting](https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_1_4_30)

**Comment by kvesteri** [comment]
The way you approached this issue sounds good. You can submit a PR 👍
