### ISSUE TITLE
use unittest.mock instead of mock in tests/types/test_password.py

### ISSUE THREAD

**Issue by pgajdos** [kvesteri/sqlalchemy-utils#594]
Could you please consider to utilize unittest.mock, as a fallback at least?

**Comment by kurtmckee** [comment]
For what reason?

**Comment by pgajdos** [comment]
For sake of simplicity -- keeping unnecessary dependencies out.
https://trello.com/c/S6eADbii/64-remove-python-mock
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by kurtmckee** [comment]
Huh. The last time I looked at mock it was still introducing new features...must have been a long time ago. I didn't realize it had moved to backport-only mode after getting introduced to the standard library.

Thanks for this info, @pgajdos!

**Comment by pgajdos** [comment]
Yes, it is still developed as 'rolling backport of the standard library mock code compatible with Python 3.6 and up'. I have tested with python 3.8, 3.9 and 3.10 that unittest.mock suffices to the testsuite currently. If you want to stay with mock, it is possible to fallback to unittest.mock when mock is not installed.

**Comment by pgajdos** [comment]
Thanks!
