### ISSUE TITLE
Sqlalchemy alembic migration error 

### ISSUE THREAD

**Issue by Tamunonengiyeofori** [kvesteri/sqlalchemy-utils#634]
Please I am having issues migrating some DB tables with sqlalchemy and alembic because of a foreign key error. I need help to resolve it. 
![image](https://user-images.githubusercontent.com/78642266/188652508-04374a53-9d38-4e10-ab57-a42ac4f6e964.png)

**Comment by kurtmckee** [comment]
@Tamunonengiyeofori, this does not appear to be related to sqlalchemy-utils. sqlalchemy-utils is a separate project from sqlalchemy.

You will need to search the internet for a solution, and possibly read the sqlalchemy documentation about this error. After doing that, if nothing resolves the issue, you may need to post in an appropriate place, such as StackOverflow. Good luck!
