### ISSUE TITLE
What happened to get_query_entities?

### ISSUE THREAD

**Issue by flewellyn** [kvesteri/sqlalchemy-utils#639]
I have an older project using SQLAlchemy and SQLAlchemy_utils, and I wanted to upgrade to using SQLAlchemy 1.4 and a corresponding version of SQLAlchemy_utils.  However, on doing so, I found that several functions I had come to rely on in SQLAlchemy_utils were no longer present, especially get_query_entities.  I was forced to revert to an earlier version to keep my code working.

Why was this removed, and how can I compensate for its lack?  I saw that the removal took place in release 0.37.0, but there was no explanation given for why the function was removed.  Nor any for sort_query, another function I have found useful.

Please advise: how can I work around the lack of get_query_entities?

**Comment by kvesteri** [comment]
SQLAlchemy changed the internals of query entities multiple times (recently also with SA 2 release). Hopefully in the future SQLAlchemy will provide native support for entity inspection via `sqlalchemy.inspect` function.
