### ISSUE TITLE
Incorrect default email length 255.

### ISSUE THREAD

**Issue by jenstroeger** [kvesteri/sqlalchemy-utils#658]
The default length of a string to store an email is currently 255:

https://github.com/kvesteri/sqlalchemy-utils/blob/5c4ca8ca98aba2fcbddd0d9ad455668286d94f8d/sqlalchemy_utils/types/email.py#L38

However, according to the [RFC](https://www.rfc-editor.org/errata/eid1690) and also [this discussion](https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address#574698) the maximum length of an email address is 254:

> In addition to restrictions on syntax, there is a length limit on
>   email addresses.  That limit is a maximum of 64 characters (octets)
>   in the "local part" (before the "@") and a maximum of 255 characters
>   (octets) in the domain part (after the "@") for a total length of 320
>   characters. However, there is a restriction in RFC 2821 on the length of an
>   address in MAIL and RCPT commands of 254 characters.  Since addresses
>   that do not fit in those fields are not normally useful, the upper
>   limit on address lengths should normally be considered to be 254.

This is probably not a big issue but should be considered for accuracy’s sake.

(See also related old PR https://github.com/kvesteri/sqlalchemy-utils/pull/230.)

**Comment by kurtmckee** [comment]
Because the default is close to _but not less than_ the maximum; and because this is a default that can be changed as needed; and because this default has been deployed for several years; I don't currently see a reason to decrease the default to 254.

**Comment by jenstroeger** [comment]
Hmm… ok. Keeping in mind, though, that the current default enables people to store invalid email addresses, i.e. one character too long.

**Comment by kurtmckee** [comment]
It's also possible that people might store things that are convenient to store as email addresses but aren't guaranteed to be. For example, a service may want to store author email addresses listed in git commits, which may not be valid email addresses.

Developers will simply need to control their inputs and requirements. Enforcement shouldn't happen from the database layer.

**Comment by jenstroeger** [comment]
Yeah the problem of “syntactically correct” email address vs. “valid” actual email address.

> Developers will simply need to control their inputs and requirements. Enforcement shouldn't happen from the database layer.

I agree, though my OCD-driven nit-picking engineering attitude squirms a bit 😉
