### ISSUE TITLE
Release request - Python 3.11

### ISSUE THREAD

**Issue by gtmanfred** [kvesteri/sqlalchemy-utils#662]
Would it be possible to cut a release of SQLAlchemy-Utils so that we can upgrade our applications to 3.11.1?

Thanks.

**Comment by kurtmckee** [comment]
I've released sqlalchemy-utils 0.39.0. This should include fixes for sqlalchemy 2.0 beta compatibility, as well as support for Python 3.11.

**Comment by gtmanfred** [comment]
Thank you very much!
