### ISSUE TITLE
Release new version for SQLAlchemy 2.0 beta compatibility

### ISSUE THREAD

**Issue by mathiasritter** [kvesteri/sqlalchemy-utils#666]
Hello,

I am running into the issue described in #665. As far as I can see, this has been fixed on the main branch since October, see #644.

Can you please release a new version so it includes the fix? @kurtmckee @kvesteri

**Comment by kurtmckee** [comment]
I've released sqlalchemy-utils 0.39.0. This should include fixes for sqlalchemy 2.0 beta compatibility, as well as support for Python 3.11.
