### ISSUE TITLE
`create_database` and `get_bind` do not work with sqlalchemy 2.0 beta 

### ISSUE THREAD

**Issue by ThirVondukr** [kvesteri/sqlalchemy-utils#669]
Package versions (could also be found in `pyproject.toml`):

- Python version: 3.10.7 / python:3.10-slim image in CI
- sqlalchemy: 2.0.4b
- sqlalchemy-utils: 0.39.0

The culprit seems to be `functions.orm.get_bind` because in 2.0 `Engine` no longer has `.execute` method

I have a repo with reproducible example on [GitLab](https://gitlab.com/ThirVondukr/fastapi-cookiecutter/-/tree/92fa7414bce6bb93ee806242a639ba2d6cb0dd0a)
And a [CI Job](https://gitlab.com/ThirVondukr/fastapi-cookiecutter/-/jobs/3527179669)

**Comment by jenstroeger** [comment]
Running SQLA 1.4 and SQLA-Utils 0.38.2 with the [RemovedIn20Warning](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings) enabled I get the following warning:
```
sqlalchemy.exc.RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
```
with this call stack:
```
.venv/lib/python3.10/site-packages/sqlalchemy_utils/functions/database.py:494: in database_exists
    return bool(_get_scalar_result(engine, text))
.venv/lib/python3.10/site-packages/sqlalchemy_utils/functions/database.py:449: in _get_scalar_result
    return conn.scalar(sql)
.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py:1262: in scalar
    return self.execute(object_, *multiparams, **params).scalar()
.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py:1357: in execute
    util.warn_deprecated_20(
...
```
Is there a plan to [migrate to SQLA 2](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html) with this package?

**Comment by BenWolfaardt** [comment]
Hi SQLalchemy-Utils devs, I am also currently facing this same issue with slightly different output, please see here below for additional resources to above issue:

With `SQLALCHEMY_WARN_20=1`:
```
.venv/lib/python3.10/site-packages/sqlalchemy_utils/aggregates.py:511: SADeprecationWarning: The `sqlalchemy.orm.mapper()` symbol is deprecated and will be removed in a future release. For the mapper-wide event target, use the 'sqlalchemy.orm.Mapper' class.
  sa.event.listen(
.venv/lib/python3.10/site-packages/sqlalchemy_utils/proxy_dict.py:84: SADeprecationWarning: The `sqlalchemy.orm.mapper()` symbol is deprecated and will be removed in a future release. For the mapper-wide event target, use the 'sqlalchemy.orm.Mapper' class.
  sa.event.listen(sa.orm.mapper, 'expire', expire_proxy_dicts)
```

And the Traceback issue is: 
```
 File "/databases.py", line 25, in create
    create_database(engine.url)
  File ".venv/lib/python3.10/site-packages/sqlalchemy_utils/functions/database.py", line 569, in create_database
    quote(engine, database),
  File ".venv/lib/python3.10/site-packages/sqlalchemy_utils/functions/orm.py", line 528, in quote
    dialect = get_bind(mixed).dialect
  File ".venv/lib/python3.10/site-packages/sqlalchemy_utils/functions/orm.py", line 339, in get_bind
    raise TypeError(
TypeError: This method accepts only Session, Engine, Connection and declarative model objects.
```

Hoping that this helps with addressing the above issue.

**Comment by BenWolfaardt** [comment]
Dear @kvesteri, 

could you please kindly indicate whether you plan on migrating to support `SQLalchemy` v2, with stable version being released within the next week? - [source](https://www.sqlalchemy.org/blog/2023/01/19/sqlalchemy-2.0.0rc3-released/)

In terms of addressing the above issue, I've created a DRAFT PR which at least solves the 2x warnings that I found in my `stdout`. In terms of the greater issue at hand, I would gladly assist, but don't fully understand the scope of the issue. If someone would kindly give me some guidance we could try and support v2 asap. 

@kurtmckee you seem to be the go-to person in this regard? Any pointers on helping you solve the underlying issue?  

Kind regards, 
Ben

**Comment by kvesteri** [comment]
Yes it is planned that SA-Utils supports SA 2.0. PRs welcome for the needed fixes.

**Comment by kvesteri** [comment]
Fixed

**Comment by jenstroeger** [comment]
Is that PR https://github.com/kvesteri/sqlalchemy-utils/pull/690?
