### ISSUE TITLE
 sqlalchemy-utils 0.39.0 sets incorrect restrictions for python

### ISSUE THREAD

**Issue by barrelful** [kvesteri/sqlalchemy-utils#670]
@kvesteri I see other issues #663 and #652 already reported that, but this problem persists if you use poetry. 

Also regarding @kurtmckee suggestion, I don't want to set "<4.0" just because of sqlalchemy-utils in my project since no other of my dozens dependencies are this over-restrictive.

I would additionally suggest to replace python `~3.6` with `>=3.7` since Python 3.6 is EOL since 2021 (https://endoflife.date/python).

**Comment by kurtmckee** [comment]
Fixed by #664. I'm also onboard for dropping Python 3.6 support, but there's no pressing need to quite yet.
