### ISSUE TITLE
type "json" does not exist when creating my tables

### ISSUE THREAD

**Issue by kernity** [kvesteri/sqlalchemy-utils#76]
Hi, 

I'm using the sqlachemy-utils JSON type with postgresql 9.1

I know that JSON for PG exists from 9.2 but by reading the code I thought that it will do a check and use string in place of native JSON but it's not the case.

I'm not sure that the only try/catch around the import is enough...I really don't understand how it's working. Can you help me to understand ? 

```python
....
try:
    from sqlalchemy.dialects.postgresql import JSON
    has_postgres_json = True
except ImportError:
    class PostgresJSONType(sa.types.UserDefinedType):
        """
        Text search vector type for postgresql.
        """
        def get_col_spec(self):
            return 'json'

    ischema_names['json'] = PostgresJSONType
    has_postgres_json = False
....
```

Can you help me ? Thank you

Khalid

**Comment by kvesteri** [comment]
All development related to JSONType is halted since SA 1.1 will have this type natively. I'll deprecate and remove JSONType from SA-Utils at some point.
