### ISSUE TITLE
PreciseTimestamp type

### ISSUE THREAD

**Issue by jd** [kvesteri/sqlalchemy-utils#86]
MySQL does not support the same kind of precision than PostgreSQL does in timestamps. We use a custom timestamp type to store timestamps as float in MySQL instead.

https://git.openstack.org/cgit/stackforge/gnocchi/tree/gnocchi/indexer/sqlalchemy.py#n47

I wonder if it would make sense to port this to sqlalchemy-utils. If so I'd be happy to submit a patch.

**Comment by kvesteri** [comment]
I'm closing this for now. As discussed in the pull request it makes more sense to add this functionality to SQLAlchemy itself.
